/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.spa.view;

/**
 *
 * @author Andres
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmCellphone
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        itmAbout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuCustomers = new javax.swing.JMenu();
        itmCustomer = new javax.swing.JMenuItem();
        mnuAppointments = new javax.swing.JMenu();
        itmSchedule = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuContact = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itmAbout.setText("LeatherFlower SPA");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itmAbout.add(jMenuItem1);

        jMenuBar1.add(itmAbout);

        mnuCustomers.setText("Customers");

        itmCustomer.setText("List of customers");
        mnuCustomers.add(itmCustomer);

        jMenuBar1.add(mnuCustomers);

        mnuAppointments.setText("Appointments");

        itmSchedule.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSchedule.setText("Schedule Appointment");
        itmSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmScheduleActionPerformed(evt);
            }
        });
        mnuAppointments.add(itmSchedule);

        jMenuBar1.add(mnuAppointments);

        jMenu1.setText("Help");

        mnuContact.setText("Contact");
        mnuContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuContactActionPerformed(evt);
            }
        });
        jMenu1.add(mnuContact);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itmScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmScheduleActionPerformed
        FrmCustomer FrmCustomer = new FrmCustomer();
        this.setVisible(false);
        FrmCustomer.setVisible(true);
    }//GEN-LAST:event_itmScheduleActionPerformed

    private void mnuContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuContactActionPerformed
        FrmHelp FrmHelp = new FrmHelp();
        this.setVisible(false);
        FrmHelp.setVisible(true);
    }//GEN-LAST:event_mnuContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itmAbout;
    private javax.swing.JMenuItem itmCustomer;
    private javax.swing.JMenuItem itmSchedule;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuAppointments;
    private javax.swing.JMenuItem mnuContact;
    private javax.swing.JMenu mnuCustomers;
    // End of variables declaration//GEN-END:variables
}
