package ec.edu.espe.SortApp.view;

import ec.edu.espe.SortApp.controller.SortingContext;
import ec.edu.espe.SortApp.model.Numbers;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Rivera, Juan Quimbiulco DCCO-ESPE, CODEX++
 */
public class FrmSortApp extends javax.swing.JFrame {

    /**
     * Creates new form SortApp
     */
    public FrmSortApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnReturn.setOpaque(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSorting = new javax.swing.JLabel();
        btnOrganize = new javax.swing.JButton();
        txtDisorderedNumbers = new javax.swing.JTextField();
        lbDisorderedNumbers = new javax.swing.JLabel();
        lbOrderedNumbers = new javax.swing.JLabel();
        txtNumberInOrder = new javax.swing.JTextField();
        lbAlgorithm = new javax.swing.JLabel();
        txtAlgorithm = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSorting.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lbSorting.setForeground(new java.awt.Color(0, 204, 204));
        lbSorting.setText("SORTING ALGORITHMS");
        getContentPane().add(lbSorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnOrganize.setBackground(new java.awt.Color(255, 204, 204));
        btnOrganize.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        btnOrganize.setForeground(new java.awt.Color(255, 51, 51));
        btnOrganize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sort (1).png"))); // NOI18N
        btnOrganize.setText("SORT");
        btnOrganize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizeActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrganize, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtDisorderedNumbers.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtDisorderedNumbers.setToolTipText("Enter the numbers you want to order and see what algorithm was used");
        txtDisorderedNumbers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisorderedNumbersKeyTyped(evt);
            }
        });
        getContentPane().add(txtDisorderedNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 250, -1));

        lbDisorderedNumbers.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        lbDisorderedNumbers.setForeground(new java.awt.Color(0, 0, 204));
        lbDisorderedNumbers.setText("UNSORTED NUMBERS:");
        getContentPane().add(lbDisorderedNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        lbOrderedNumbers.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        lbOrderedNumbers.setForeground(new java.awt.Color(0, 0, 204));
        lbOrderedNumbers.setText("SORTED NUMBERS:");
        getContentPane().add(lbOrderedNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, -1));

        txtNumberInOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNumberInOrder.setEnabled(false);
        getContentPane().add(txtNumberInOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, 30));

        lbAlgorithm.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        lbAlgorithm.setForeground(new java.awt.Color(0, 0, 204));
        lbAlgorithm.setText("ALGORITHM USED:");
        getContentPane().add(lbAlgorithm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtAlgorithm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtAlgorithm.setEnabled(false);
        getContentPane().add(txtAlgorithm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 250, -1));

        btnReturn.setBackground(new java.awt.Color(255, 204, 204));
        btnReturn.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 0, 51));
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/undo (1).png"))); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 50, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background 3.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrganizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizeActionPerformed
        String numberInDesorder;
        SortingContext sortingContext;
        sortingContext = new SortingContext();
        numberInDesorder = txtDisorderedNumbers.getText();
        Numbers listNumbers = new Numbers();
        String[] numberToSort = numberInDesorder.split(",");
        int[] numbersOfList= new int[numberToSort.length];
        listNumbers.setUnsorted(numbersOfList);
        for (int i = 0; i < numberToSort.length; i++) {
            numbersOfList[i] = Integer.parseInt(numberToSort[i]);
        }
        
        sortingContext.setSortStrategy(numbersOfList,listNumbers);
        txtNumberInOrder.setText(Arrays.toString(listNumbers.getSorted()));
        txtAlgorithm.setText(listNumbers.getAlgorithm());
    }//GEN-LAST:event_btnOrganizeActionPerformed

    private void txtDisorderedNumbersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisorderedNumbersKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Enter only numbers, for example: 1, 2, 3, etc.. ");
      }
    }//GEN-LAST:event_txtDisorderedNumbersKeyTyped

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmMenu frmMenu = new FrmMenu();
        frmMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSortApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSortApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSortApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSortApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSortApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrganize;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbAlgorithm;
    private javax.swing.JLabel lbDisorderedNumbers;
    private javax.swing.JLabel lbOrderedNumbers;
    private javax.swing.JLabel lbSorting;
    private javax.swing.JTextField txtAlgorithm;
    private javax.swing.JTextField txtDisorderedNumbers;
    private javax.swing.JTextField txtNumberInOrder;
    // End of variables declaration//GEN-END:variables
}
