/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.store.view;

/**
 *
 * @author Daniel Chiriboga, DCCO-ESPE, DAMAGE SE
 */
public class FrmBakery extends javax.swing.JFrame {

    /**
     * Creates new form FrmBakery
     */
    public FrmBakery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuBakery = new javax.swing.JMenu();
        itemAbout = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();
        mnuProduct = new javax.swing.JMenu();
        itemMagement = new javax.swing.JMenuItem();
        nmuBreads = new javax.swing.JMenu();
        itemAddToStock = new javax.swing.JMenuItem();
        itemSell = new javax.swing.JMenuItem();
        mnuCustomer = new javax.swing.JMenu();
        itemAddCustomers = new javax.swing.JMenuItem();
        nmuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuBakery.setText("Bakery");

        itemAbout.setText("About");
        itemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutActionPerformed(evt);
            }
        });
        mnuBakery.add(itemAbout);

        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        mnuBakery.add(itemExit);

        jMenuBar1.add(mnuBakery);

        mnuProduct.setText("Product");

        itemMagement.setText("Management");
        itemMagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMagementActionPerformed(evt);
            }
        });
        mnuProduct.add(itemMagement);

        jMenuBar1.add(mnuProduct);

        nmuBreads.setText("Breads");

        itemAddToStock.setText("Add to stock");
        itemAddToStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddToStockActionPerformed(evt);
            }
        });
        nmuBreads.add(itemAddToStock);

        itemSell.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemSell.setText("Sell");
        itemSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSellActionPerformed(evt);
            }
        });
        nmuBreads.add(itemSell);

        jMenuBar1.add(nmuBreads);

        mnuCustomer.setText("Customer");

        itemAddCustomers.setText("Customers");
        itemAddCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddCustomersActionPerformed(evt);
            }
        });
        mnuCustomer.add(itemAddCustomers);

        jMenuBar1.add(mnuCustomer);

        nmuHelp.setText("Help");
        jMenuBar1.add(nmuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSellActionPerformed
        FrmSell view = new FrmSell();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemSellActionPerformed

    private void itemMagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMagementActionPerformed

    }//GEN-LAST:event_itemMagementActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemAddCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddCustomersActionPerformed
        FrmCustomers view = new FrmCustomers();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemAddCustomersActionPerformed

    private void itemAddToStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddToStockActionPerformed
        FrmBread view = new FrmBread();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemAddToStockActionPerformed

    private void itemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutActionPerformed
        FrmAbout view = new FrmAbout();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBakery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbout;
    private javax.swing.JMenuItem itemAddCustomers;
    private javax.swing.JMenuItem itemAddToStock;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemMagement;
    private javax.swing.JMenuItem itemSell;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuBakery;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JMenu mnuProduct;
    private javax.swing.JMenu nmuBreads;
    private javax.swing.JMenu nmuHelp;
    // End of variables declaration//GEN-END:variables
}
