
package edu.espe.ec.spa.view;

/**
 *
 * @author Erick Moreira, DCCO-ESPE DEES Developers
 */
public class FrmSpaSystem extends javax.swing.JFrame {

    /**
     * Creates new form FrmSpaSystem
     */
    public FrmSpaSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSpaSystem = new javax.swing.JMenu();
        itmAbout = new javax.swing.JMenuItem();
        mnuService = new javax.swing.JMenu();
        itmService = new javax.swing.JMenuItem();
        mnuAppointment = new javax.swing.JMenu();
        itmSchedule = new javax.swing.JMenuItem();
        itmCancel = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuSpaSystem.setText("SpaSystem");

        itmAbout.setText("About");
        mnuSpaSystem.add(itmAbout);

        jMenuBar1.add(mnuSpaSystem);

        mnuService.setText("Service");
        mnuService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuServiceActionPerformed(evt);
            }
        });

        itmService.setText("Management");
        itmService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmServiceActionPerformed(evt);
            }
        });
        mnuService.add(itmService);

        jMenuBar1.add(mnuService);

        mnuAppointment.setText("Appointment");

        itmSchedule.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itmSchedule.setText("Schedule");
        itmSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmScheduleActionPerformed(evt);
            }
        });
        mnuAppointment.add(itmSchedule);

        itmCancel.setText("Cancel");
        mnuAppointment.add(itmCancel);

        jMenuBar1.add(mnuAppointment);

        mnuHelp.setText("Help");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmScheduleActionPerformed
        FrmSpa frmSpa;
        frmSpa = new FrmSpa();
        this.setVisible(false);
        frmSpa.setVisible(true);
    }//GEN-LAST:event_itmScheduleActionPerformed

    private void mnuServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuServiceActionPerformed
        FrmService frmService;
        frmService = new FrmService();
        frmService.setVisible(true);
    }//GEN-LAST:event_mnuServiceActionPerformed

    private void itmServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmServiceActionPerformed
        FrmService frmService;
        frmService = new FrmService();
        frmService.setVisible(true);
    }//GEN-LAST:event_itmServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSpaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSpaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSpaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSpaSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSpaSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAbout;
    private javax.swing.JMenuItem itmCancel;
    private javax.swing.JMenuItem itmSchedule;
    private javax.swing.JMenuItem itmService;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAppointment;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuService;
    private javax.swing.JMenu mnuSpaSystem;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
